In [1]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
import pandas as pd

In [3]:
da=pd.read_csv('/home/aayush/Downloads/digits.csv')
da.head()

88   92    2   99   16   66   94   37   70    0    0.1   24   42   65  \
0   80  100   18   98   60   66  100   29   42    0      0   23   42   61   
1    0   94    9   57   20   19    7    0   20   36     70   68  100  100   
2   95   82   71  100   27   77   77   73  100   80     93   42   56   13   
3   68  100    6   88   47   75   87   82   85   56    100   29   75    6   
4   70  100  100   97   70   81   45   65   30   49     20   33    0   16   

   100  100.1   8  
0   56     98   8  
1   18     92   8  
2    0      0   9  
3    0      0   9  
4    0      0   1

In [4]:
da=np.asarray(da[:2000])
print(da[:10])
np.random.shuffle(da)
da.shape

[[ 80 100  18  98  60  66 100  29  42   0   0  23  42  61  56  98   8]
 [  0  94   9  57  20  19   7   0  20  36  70  68 100 100  18  92   8]
 [ 95  82  71 100  27  77  77  73 100  80  93  42  56  13   0   0   9]
 [ 68 100   6  88  47  75  87  82  85  56 100  29  75   6   0   0   9]
 [ 70 100 100  97  70  81  45  65  30  49  20  33   0  16   0   0   1]
 [ 40 100   0  81  15  58 100  57  47  87  50  88  40  42  36   0   4]
 [  3  71   0  95  45 100 100  99  79  78  48  53  31  24  54   0   7]
 [ 79  87  98  81  71 100  72  73 100  66  91  21  48   0   0  13   9]
 [ 92  95  30 100  34  68  87  89  84  78 100  35  64   0   0  19   9]
 [ 58  64 100  96  27 100   0  63  79  65  91  72  48  36  10   0   9]]


(2000, 17)

In [5]:
split=int(0.9 * da.shape[0])
print(split)
xtrain=da[:split,:-1]
xtest=da[split:,:-1]

ytrain=da[:split,-1]
ytest=da[split:,-1]

print(xtest.shape)

1800
(200, 16)


In [6]:
from scipy import spatial

In [7]:
def dist(x1,x2):
    d=(spatial.distance.cosine(x1, x2))
    return d

def knearn(xtrain,ytrain,xtest,k=5):
    vals=[]
    for i in range(xtrain.shape[0]):
        d=dist(xtrain[i],xtest)
        vals.append([d,ytrain[i]])
    sortedd=sorted(vals,key=lambda x:x[0])
    sortedd=np.asarray(sortedd)
    neigh=sortedd[:k,-1]
    freq=np.unique(neigh,return_counts=True)
    return(freq[0][freq[1].argmax()])

In [8]:
def gacc(kx):
    pred=[]
    for iac in range(xtest.shape[0]):
        pred.append(knearn(xtrain,ytrain,xtest[iac],kx))
    pred=np.asarray(pred)
    for ig in range(pred.shape[0]):
        if(pred[ig]==ytest[ig]):
            print("True")
        else:
            print("False")
    return 100*float((ytest == pred).sum())/pred.shape[0]
print(gacc(3))
        

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
Tru